### ISSUE TITLE
Erro ao executar o gera_sql.sh

### ISSUE THREAD

**Issue by sandrobrz2** [eleicao2022/eleicao_2022#2]
Estou executando atraves do docker a maquina linux.
Fiz todos os passos anteriores com sucesso.
Mas recebo esses erros ao executar o gera_sql.sh

Traceback (most recent call last):
  File "/home/sandro/Desktop/Eleicao/scripts/../src/gerar_sql_votos.py", line 23, in <module>
    asn1 = asn1tools.compile_files("./bu.asn1", codec="ber")
  File "/usr/local/lib/python3.10/dist-packages/asn1tools/compiler.py", line 376, in compile_files
    return compile_dict(parse_files(filenames, encoding),
  File "/usr/local/lib/python3.10/dist-packages/asn1tools/parser.py", line 1889, in parse_files
    with open(filename, 'r', encoding=encoding, errors='replace') as fin:
FileNotFoundError: [Errno 2] No such file or directory: './bu.asn1'

obs : o asnltools esta instalado.

**Comment by sandrobrz2** [comment]
Resolvido, era problema de path
